
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Drop` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Drop
 * 
 */
export type DropModel = runtime.Types.Result.DefaultSelection<Prisma.$DropPayload>

export type AggregateDrop = {
  _count: DropCountAggregateOutputType | null
  _avg: DropAvgAggregateOutputType | null
  _sum: DropSumAggregateOutputType | null
  _min: DropMinAggregateOutputType | null
  _max: DropMaxAggregateOutputType | null
}

export type DropAvgAggregateOutputType = {
  price: number | null
  availableStock: number | null
}

export type DropSumAggregateOutputType = {
  price: number | null
  availableStock: number | null
}

export type DropMinAggregateOutputType = {
  id: string | null
  name: string | null
  price: number | null
  availableStock: number | null
  createdAt: Date | null
}

export type DropMaxAggregateOutputType = {
  id: string | null
  name: string | null
  price: number | null
  availableStock: number | null
  createdAt: Date | null
}

export type DropCountAggregateOutputType = {
  id: number
  name: number
  price: number
  availableStock: number
  createdAt: number
  _all: number
}


export type DropAvgAggregateInputType = {
  price?: true
  availableStock?: true
}

export type DropSumAggregateInputType = {
  price?: true
  availableStock?: true
}

export type DropMinAggregateInputType = {
  id?: true
  name?: true
  price?: true
  availableStock?: true
  createdAt?: true
}

export type DropMaxAggregateInputType = {
  id?: true
  name?: true
  price?: true
  availableStock?: true
  createdAt?: true
}

export type DropCountAggregateInputType = {
  id?: true
  name?: true
  price?: true
  availableStock?: true
  createdAt?: true
  _all?: true
}

export type DropAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Drop to aggregate.
   */
  where?: Prisma.DropWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Drops to fetch.
   */
  orderBy?: Prisma.DropOrderByWithRelationInput | Prisma.DropOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DropWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Drops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Drops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Drops
  **/
  _count?: true | DropCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DropAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DropSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DropMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DropMaxAggregateInputType
}

export type GetDropAggregateType<T extends DropAggregateArgs> = {
      [P in keyof T & keyof AggregateDrop]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDrop[P]>
    : Prisma.GetScalarType<T[P], AggregateDrop[P]>
}




export type DropGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DropWhereInput
  orderBy?: Prisma.DropOrderByWithAggregationInput | Prisma.DropOrderByWithAggregationInput[]
  by: Prisma.DropScalarFieldEnum[] | Prisma.DropScalarFieldEnum
  having?: Prisma.DropScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DropCountAggregateInputType | true
  _avg?: DropAvgAggregateInputType
  _sum?: DropSumAggregateInputType
  _min?: DropMinAggregateInputType
  _max?: DropMaxAggregateInputType
}

export type DropGroupByOutputType = {
  id: string
  name: string
  price: number
  availableStock: number
  createdAt: Date
  _count: DropCountAggregateOutputType | null
  _avg: DropAvgAggregateOutputType | null
  _sum: DropSumAggregateOutputType | null
  _min: DropMinAggregateOutputType | null
  _max: DropMaxAggregateOutputType | null
}

export type GetDropGroupByPayload<T extends DropGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DropGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DropGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DropGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DropGroupByOutputType[P]>
      }
    >
  >



export type DropWhereInput = {
  AND?: Prisma.DropWhereInput | Prisma.DropWhereInput[]
  OR?: Prisma.DropWhereInput[]
  NOT?: Prisma.DropWhereInput | Prisma.DropWhereInput[]
  id?: Prisma.StringFilter<"Drop"> | string
  name?: Prisma.StringFilter<"Drop"> | string
  price?: Prisma.FloatFilter<"Drop"> | number
  availableStock?: Prisma.IntFilter<"Drop"> | number
  createdAt?: Prisma.DateTimeFilter<"Drop"> | Date | string
  reservations?: Prisma.ReservationListRelationFilter
  purchases?: Prisma.PurchaseListRelationFilter
}

export type DropOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  availableStock?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  reservations?: Prisma.ReservationOrderByRelationAggregateInput
  purchases?: Prisma.PurchaseOrderByRelationAggregateInput
}

export type DropWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DropWhereInput | Prisma.DropWhereInput[]
  OR?: Prisma.DropWhereInput[]
  NOT?: Prisma.DropWhereInput | Prisma.DropWhereInput[]
  name?: Prisma.StringFilter<"Drop"> | string
  price?: Prisma.FloatFilter<"Drop"> | number
  availableStock?: Prisma.IntFilter<"Drop"> | number
  createdAt?: Prisma.DateTimeFilter<"Drop"> | Date | string
  reservations?: Prisma.ReservationListRelationFilter
  purchases?: Prisma.PurchaseListRelationFilter
}, "id">

export type DropOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  availableStock?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.DropCountOrderByAggregateInput
  _avg?: Prisma.DropAvgOrderByAggregateInput
  _max?: Prisma.DropMaxOrderByAggregateInput
  _min?: Prisma.DropMinOrderByAggregateInput
  _sum?: Prisma.DropSumOrderByAggregateInput
}

export type DropScalarWhereWithAggregatesInput = {
  AND?: Prisma.DropScalarWhereWithAggregatesInput | Prisma.DropScalarWhereWithAggregatesInput[]
  OR?: Prisma.DropScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DropScalarWhereWithAggregatesInput | Prisma.DropScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Drop"> | string
  name?: Prisma.StringWithAggregatesFilter<"Drop"> | string
  price?: Prisma.FloatWithAggregatesFilter<"Drop"> | number
  availableStock?: Prisma.IntWithAggregatesFilter<"Drop"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Drop"> | Date | string
}

export type DropCreateInput = {
  id?: string
  name: string
  price: number
  availableStock?: number
  createdAt?: Date | string
  reservations?: Prisma.ReservationCreateNestedManyWithoutDropInput
  purchases?: Prisma.PurchaseCreateNestedManyWithoutDropInput
}

export type DropUncheckedCreateInput = {
  id?: string
  name: string
  price: number
  availableStock?: number
  createdAt?: Date | string
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutDropInput
  purchases?: Prisma.PurchaseUncheckedCreateNestedManyWithoutDropInput
}

export type DropUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  availableStock?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUpdateManyWithoutDropNestedInput
  purchases?: Prisma.PurchaseUpdateManyWithoutDropNestedInput
}

export type DropUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  availableStock?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutDropNestedInput
  purchases?: Prisma.PurchaseUncheckedUpdateManyWithoutDropNestedInput
}

export type DropCreateManyInput = {
  id?: string
  name: string
  price: number
  availableStock?: number
  createdAt?: Date | string
}

export type DropUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  availableStock?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DropUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  availableStock?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DropCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  availableStock?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DropAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
  availableStock?: Prisma.SortOrder
}

export type DropMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  availableStock?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DropMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  availableStock?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DropSumOrderByAggregateInput = {
  price?: Prisma.SortOrder
  availableStock?: Prisma.SortOrder
}

export type DropScalarRelationFilter = {
  is?: Prisma.DropWhereInput
  isNot?: Prisma.DropWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type DropCreateNestedOneWithoutReservationsInput = {
  create?: Prisma.XOR<Prisma.DropCreateWithoutReservationsInput, Prisma.DropUncheckedCreateWithoutReservationsInput>
  connectOrCreate?: Prisma.DropCreateOrConnectWithoutReservationsInput
  connect?: Prisma.DropWhereUniqueInput
}

export type DropUpdateOneRequiredWithoutReservationsNestedInput = {
  create?: Prisma.XOR<Prisma.DropCreateWithoutReservationsInput, Prisma.DropUncheckedCreateWithoutReservationsInput>
  connectOrCreate?: Prisma.DropCreateOrConnectWithoutReservationsInput
  upsert?: Prisma.DropUpsertWithoutReservationsInput
  connect?: Prisma.DropWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DropUpdateToOneWithWhereWithoutReservationsInput, Prisma.DropUpdateWithoutReservationsInput>, Prisma.DropUncheckedUpdateWithoutReservationsInput>
}

export type DropCreateNestedOneWithoutPurchasesInput = {
  create?: Prisma.XOR<Prisma.DropCreateWithoutPurchasesInput, Prisma.DropUncheckedCreateWithoutPurchasesInput>
  connectOrCreate?: Prisma.DropCreateOrConnectWithoutPurchasesInput
  connect?: Prisma.DropWhereUniqueInput
}

export type DropUpdateOneRequiredWithoutPurchasesNestedInput = {
  create?: Prisma.XOR<Prisma.DropCreateWithoutPurchasesInput, Prisma.DropUncheckedCreateWithoutPurchasesInput>
  connectOrCreate?: Prisma.DropCreateOrConnectWithoutPurchasesInput
  upsert?: Prisma.DropUpsertWithoutPurchasesInput
  connect?: Prisma.DropWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DropUpdateToOneWithWhereWithoutPurchasesInput, Prisma.DropUpdateWithoutPurchasesInput>, Prisma.DropUncheckedUpdateWithoutPurchasesInput>
}

export type DropCreateWithoutReservationsInput = {
  id?: string
  name: string
  price: number
  availableStock?: number
  createdAt?: Date | string
  purchases?: Prisma.PurchaseCreateNestedManyWithoutDropInput
}

export type DropUncheckedCreateWithoutReservationsInput = {
  id?: string
  name: string
  price: number
  availableStock?: number
  createdAt?: Date | string
  purchases?: Prisma.PurchaseUncheckedCreateNestedManyWithoutDropInput
}

export type DropCreateOrConnectWithoutReservationsInput = {
  where: Prisma.DropWhereUniqueInput
  create: Prisma.XOR<Prisma.DropCreateWithoutReservationsInput, Prisma.DropUncheckedCreateWithoutReservationsInput>
}

export type DropUpsertWithoutReservationsInput = {
  update: Prisma.XOR<Prisma.DropUpdateWithoutReservationsInput, Prisma.DropUncheckedUpdateWithoutReservationsInput>
  create: Prisma.XOR<Prisma.DropCreateWithoutReservationsInput, Prisma.DropUncheckedCreateWithoutReservationsInput>
  where?: Prisma.DropWhereInput
}

export type DropUpdateToOneWithWhereWithoutReservationsInput = {
  where?: Prisma.DropWhereInput
  data: Prisma.XOR<Prisma.DropUpdateWithoutReservationsInput, Prisma.DropUncheckedUpdateWithoutReservationsInput>
}

export type DropUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  availableStock?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  purchases?: Prisma.PurchaseUpdateManyWithoutDropNestedInput
}

export type DropUncheckedUpdateWithoutReservationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  availableStock?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  purchases?: Prisma.PurchaseUncheckedUpdateManyWithoutDropNestedInput
}

export type DropCreateWithoutPurchasesInput = {
  id?: string
  name: string
  price: number
  availableStock?: number
  createdAt?: Date | string
  reservations?: Prisma.ReservationCreateNestedManyWithoutDropInput
}

export type DropUncheckedCreateWithoutPurchasesInput = {
  id?: string
  name: string
  price: number
  availableStock?: number
  createdAt?: Date | string
  reservations?: Prisma.ReservationUncheckedCreateNestedManyWithoutDropInput
}

export type DropCreateOrConnectWithoutPurchasesInput = {
  where: Prisma.DropWhereUniqueInput
  create: Prisma.XOR<Prisma.DropCreateWithoutPurchasesInput, Prisma.DropUncheckedCreateWithoutPurchasesInput>
}

export type DropUpsertWithoutPurchasesInput = {
  update: Prisma.XOR<Prisma.DropUpdateWithoutPurchasesInput, Prisma.DropUncheckedUpdateWithoutPurchasesInput>
  create: Prisma.XOR<Prisma.DropCreateWithoutPurchasesInput, Prisma.DropUncheckedCreateWithoutPurchasesInput>
  where?: Prisma.DropWhereInput
}

export type DropUpdateToOneWithWhereWithoutPurchasesInput = {
  where?: Prisma.DropWhereInput
  data: Prisma.XOR<Prisma.DropUpdateWithoutPurchasesInput, Prisma.DropUncheckedUpdateWithoutPurchasesInput>
}

export type DropUpdateWithoutPurchasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  availableStock?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUpdateManyWithoutDropNestedInput
}

export type DropUncheckedUpdateWithoutPurchasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  availableStock?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reservations?: Prisma.ReservationUncheckedUpdateManyWithoutDropNestedInput
}


/**
 * Count Type DropCountOutputType
 */

export type DropCountOutputType = {
  reservations: number
  purchases: number
}

export type DropCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reservations?: boolean | DropCountOutputTypeCountReservationsArgs
  purchases?: boolean | DropCountOutputTypeCountPurchasesArgs
}

/**
 * DropCountOutputType without action
 */
export type DropCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropCountOutputType
   */
  select?: Prisma.DropCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DropCountOutputType without action
 */
export type DropCountOutputTypeCountReservationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReservationWhereInput
}

/**
 * DropCountOutputType without action
 */
export type DropCountOutputTypeCountPurchasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PurchaseWhereInput
}


export type DropSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  availableStock?: boolean
  createdAt?: boolean
  reservations?: boolean | Prisma.Drop$reservationsArgs<ExtArgs>
  purchases?: boolean | Prisma.Drop$purchasesArgs<ExtArgs>
  _count?: boolean | Prisma.DropCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["drop"]>

export type DropSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  availableStock?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["drop"]>

export type DropSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  availableStock?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["drop"]>

export type DropSelectScalar = {
  id?: boolean
  name?: boolean
  price?: boolean
  availableStock?: boolean
  createdAt?: boolean
}

export type DropOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "price" | "availableStock" | "createdAt", ExtArgs["result"]["drop"]>
export type DropInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reservations?: boolean | Prisma.Drop$reservationsArgs<ExtArgs>
  purchases?: boolean | Prisma.Drop$purchasesArgs<ExtArgs>
  _count?: boolean | Prisma.DropCountOutputTypeDefaultArgs<ExtArgs>
}
export type DropIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type DropIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $DropPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Drop"
  objects: {
    reservations: Prisma.$ReservationPayload<ExtArgs>[]
    purchases: Prisma.$PurchasePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    price: number
    availableStock: number
    createdAt: Date
  }, ExtArgs["result"]["drop"]>
  composites: {}
}

export type DropGetPayload<S extends boolean | null | undefined | DropDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DropPayload, S>

export type DropCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DropFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DropCountAggregateInputType | true
  }

export interface DropDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Drop'], meta: { name: 'Drop' } }
  /**
   * Find zero or one Drop that matches the filter.
   * @param {DropFindUniqueArgs} args - Arguments to find a Drop
   * @example
   * // Get one Drop
   * const drop = await prisma.drop.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DropFindUniqueArgs>(args: Prisma.SelectSubset<T, DropFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DropClient<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Drop that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DropFindUniqueOrThrowArgs} args - Arguments to find a Drop
   * @example
   * // Get one Drop
   * const drop = await prisma.drop.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DropFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DropFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DropClient<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Drop that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropFindFirstArgs} args - Arguments to find a Drop
   * @example
   * // Get one Drop
   * const drop = await prisma.drop.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DropFindFirstArgs>(args?: Prisma.SelectSubset<T, DropFindFirstArgs<ExtArgs>>): Prisma.Prisma__DropClient<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Drop that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropFindFirstOrThrowArgs} args - Arguments to find a Drop
   * @example
   * // Get one Drop
   * const drop = await prisma.drop.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DropFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DropFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DropClient<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Drops that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Drops
   * const drops = await prisma.drop.findMany()
   * 
   * // Get first 10 Drops
   * const drops = await prisma.drop.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dropWithIdOnly = await prisma.drop.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DropFindManyArgs>(args?: Prisma.SelectSubset<T, DropFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Drop.
   * @param {DropCreateArgs} args - Arguments to create a Drop.
   * @example
   * // Create one Drop
   * const Drop = await prisma.drop.create({
   *   data: {
   *     // ... data to create a Drop
   *   }
   * })
   * 
   */
  create<T extends DropCreateArgs>(args: Prisma.SelectSubset<T, DropCreateArgs<ExtArgs>>): Prisma.Prisma__DropClient<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Drops.
   * @param {DropCreateManyArgs} args - Arguments to create many Drops.
   * @example
   * // Create many Drops
   * const drop = await prisma.drop.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DropCreateManyArgs>(args?: Prisma.SelectSubset<T, DropCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Drops and returns the data saved in the database.
   * @param {DropCreateManyAndReturnArgs} args - Arguments to create many Drops.
   * @example
   * // Create many Drops
   * const drop = await prisma.drop.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Drops and only return the `id`
   * const dropWithIdOnly = await prisma.drop.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DropCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DropCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Drop.
   * @param {DropDeleteArgs} args - Arguments to delete one Drop.
   * @example
   * // Delete one Drop
   * const Drop = await prisma.drop.delete({
   *   where: {
   *     // ... filter to delete one Drop
   *   }
   * })
   * 
   */
  delete<T extends DropDeleteArgs>(args: Prisma.SelectSubset<T, DropDeleteArgs<ExtArgs>>): Prisma.Prisma__DropClient<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Drop.
   * @param {DropUpdateArgs} args - Arguments to update one Drop.
   * @example
   * // Update one Drop
   * const drop = await prisma.drop.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DropUpdateArgs>(args: Prisma.SelectSubset<T, DropUpdateArgs<ExtArgs>>): Prisma.Prisma__DropClient<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Drops.
   * @param {DropDeleteManyArgs} args - Arguments to filter Drops to delete.
   * @example
   * // Delete a few Drops
   * const { count } = await prisma.drop.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DropDeleteManyArgs>(args?: Prisma.SelectSubset<T, DropDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Drops.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Drops
   * const drop = await prisma.drop.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DropUpdateManyArgs>(args: Prisma.SelectSubset<T, DropUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Drops and returns the data updated in the database.
   * @param {DropUpdateManyAndReturnArgs} args - Arguments to update many Drops.
   * @example
   * // Update many Drops
   * const drop = await prisma.drop.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Drops and only return the `id`
   * const dropWithIdOnly = await prisma.drop.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DropUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DropUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Drop.
   * @param {DropUpsertArgs} args - Arguments to update or create a Drop.
   * @example
   * // Update or create a Drop
   * const drop = await prisma.drop.upsert({
   *   create: {
   *     // ... data to create a Drop
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Drop we want to update
   *   }
   * })
   */
  upsert<T extends DropUpsertArgs>(args: Prisma.SelectSubset<T, DropUpsertArgs<ExtArgs>>): Prisma.Prisma__DropClient<runtime.Types.Result.GetResult<Prisma.$DropPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Drops.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropCountArgs} args - Arguments to filter Drops to count.
   * @example
   * // Count the number of Drops
   * const count = await prisma.drop.count({
   *   where: {
   *     // ... the filter for the Drops we want to count
   *   }
   * })
  **/
  count<T extends DropCountArgs>(
    args?: Prisma.Subset<T, DropCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DropCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Drop.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DropAggregateArgs>(args: Prisma.Subset<T, DropAggregateArgs>): Prisma.PrismaPromise<GetDropAggregateType<T>>

  /**
   * Group by Drop.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DropGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DropGroupByArgs['orderBy'] }
      : { orderBy?: DropGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DropGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDropGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Drop model
 */
readonly fields: DropFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Drop.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DropClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  reservations<T extends Prisma.Drop$reservationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Drop$reservationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReservationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  purchases<T extends Prisma.Drop$purchasesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Drop$purchasesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PurchasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Drop model
 */
export interface DropFieldRefs {
  readonly id: Prisma.FieldRef<"Drop", 'String'>
  readonly name: Prisma.FieldRef<"Drop", 'String'>
  readonly price: Prisma.FieldRef<"Drop", 'Float'>
  readonly availableStock: Prisma.FieldRef<"Drop", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Drop", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Drop findUnique
 */
export type DropFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * Filter, which Drop to fetch.
   */
  where: Prisma.DropWhereUniqueInput
}

/**
 * Drop findUniqueOrThrow
 */
export type DropFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * Filter, which Drop to fetch.
   */
  where: Prisma.DropWhereUniqueInput
}

/**
 * Drop findFirst
 */
export type DropFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * Filter, which Drop to fetch.
   */
  where?: Prisma.DropWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Drops to fetch.
   */
  orderBy?: Prisma.DropOrderByWithRelationInput | Prisma.DropOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Drops.
   */
  cursor?: Prisma.DropWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Drops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Drops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Drops.
   */
  distinct?: Prisma.DropScalarFieldEnum | Prisma.DropScalarFieldEnum[]
}

/**
 * Drop findFirstOrThrow
 */
export type DropFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * Filter, which Drop to fetch.
   */
  where?: Prisma.DropWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Drops to fetch.
   */
  orderBy?: Prisma.DropOrderByWithRelationInput | Prisma.DropOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Drops.
   */
  cursor?: Prisma.DropWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Drops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Drops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Drops.
   */
  distinct?: Prisma.DropScalarFieldEnum | Prisma.DropScalarFieldEnum[]
}

/**
 * Drop findMany
 */
export type DropFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * Filter, which Drops to fetch.
   */
  where?: Prisma.DropWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Drops to fetch.
   */
  orderBy?: Prisma.DropOrderByWithRelationInput | Prisma.DropOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Drops.
   */
  cursor?: Prisma.DropWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Drops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Drops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Drops.
   */
  distinct?: Prisma.DropScalarFieldEnum | Prisma.DropScalarFieldEnum[]
}

/**
 * Drop create
 */
export type DropCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * The data needed to create a Drop.
   */
  data: Prisma.XOR<Prisma.DropCreateInput, Prisma.DropUncheckedCreateInput>
}

/**
 * Drop createMany
 */
export type DropCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Drops.
   */
  data: Prisma.DropCreateManyInput | Prisma.DropCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Drop createManyAndReturn
 */
export type DropCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * The data used to create many Drops.
   */
  data: Prisma.DropCreateManyInput | Prisma.DropCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Drop update
 */
export type DropUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * The data needed to update a Drop.
   */
  data: Prisma.XOR<Prisma.DropUpdateInput, Prisma.DropUncheckedUpdateInput>
  /**
   * Choose, which Drop to update.
   */
  where: Prisma.DropWhereUniqueInput
}

/**
 * Drop updateMany
 */
export type DropUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Drops.
   */
  data: Prisma.XOR<Prisma.DropUpdateManyMutationInput, Prisma.DropUncheckedUpdateManyInput>
  /**
   * Filter which Drops to update
   */
  where?: Prisma.DropWhereInput
  /**
   * Limit how many Drops to update.
   */
  limit?: number
}

/**
 * Drop updateManyAndReturn
 */
export type DropUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * The data used to update Drops.
   */
  data: Prisma.XOR<Prisma.DropUpdateManyMutationInput, Prisma.DropUncheckedUpdateManyInput>
  /**
   * Filter which Drops to update
   */
  where?: Prisma.DropWhereInput
  /**
   * Limit how many Drops to update.
   */
  limit?: number
}

/**
 * Drop upsert
 */
export type DropUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * The filter to search for the Drop to update in case it exists.
   */
  where: Prisma.DropWhereUniqueInput
  /**
   * In case the Drop found by the `where` argument doesn't exist, create a new Drop with this data.
   */
  create: Prisma.XOR<Prisma.DropCreateInput, Prisma.DropUncheckedCreateInput>
  /**
   * In case the Drop was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DropUpdateInput, Prisma.DropUncheckedUpdateInput>
}

/**
 * Drop delete
 */
export type DropDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
  /**
   * Filter which Drop to delete.
   */
  where: Prisma.DropWhereUniqueInput
}

/**
 * Drop deleteMany
 */
export type DropDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Drops to delete
   */
  where?: Prisma.DropWhereInput
  /**
   * Limit how many Drops to delete.
   */
  limit?: number
}

/**
 * Drop.reservations
 */
export type Drop$reservationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reservation
   */
  select?: Prisma.ReservationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reservation
   */
  omit?: Prisma.ReservationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReservationInclude<ExtArgs> | null
  where?: Prisma.ReservationWhereInput
  orderBy?: Prisma.ReservationOrderByWithRelationInput | Prisma.ReservationOrderByWithRelationInput[]
  cursor?: Prisma.ReservationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReservationScalarFieldEnum | Prisma.ReservationScalarFieldEnum[]
}

/**
 * Drop.purchases
 */
export type Drop$purchasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Purchase
   */
  select?: Prisma.PurchaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Purchase
   */
  omit?: Prisma.PurchaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PurchaseInclude<ExtArgs> | null
  where?: Prisma.PurchaseWhereInput
  orderBy?: Prisma.PurchaseOrderByWithRelationInput | Prisma.PurchaseOrderByWithRelationInput[]
  cursor?: Prisma.PurchaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PurchaseScalarFieldEnum | Prisma.PurchaseScalarFieldEnum[]
}

/**
 * Drop without action
 */
export type DropDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Drop
   */
  select?: Prisma.DropSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Drop
   */
  omit?: Prisma.DropOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropInclude<ExtArgs> | null
}
